language: java

jdk:
 - oraclejdk7
 - openjdk7

install: ./gradlew assemble
script: ./gradlew check --stacktrace --info
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
